# Generated by Django 6.0 on 2025-12-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_car_buyer_car_updated_at_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
